# Generated by Django 5.2.4 on 2025-07-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('fire', 'Fire Safety'), ('ict', 'ICT/Telecommunication')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
