# Generated by Django 5.2.4 on 2025-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0004_set_category_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
