# Generated by Django 5.2.4 on 2025-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0009_remove_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Optional'),
        ),
    ]
