# Generated by Django 5.2.4 on 2025-08-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0010_product_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_tables', to='Systems.product')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(default=list)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='Systems.specificationtable')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
