# Generated by Django 5.2.4 on 2025-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0012_remove_category_type_remove_specificationrow_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('fire_safety', 'Fire Safety'), ('ict', 'ICT')], default='fire_safety', max_length=50),
        ),
        migrations.AlterField(
            model_name='specificationrow',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificationrow',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
