# Generated by Django 5.2.4 on 2025-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0013_category_type_alter_specificationrow_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='documentation_label',
            field=models.CharField(blank=True, help_text="Display text for the documentation link (e.g., 'View Datasheet', 'Technical Specs')", max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='documentation',
            field=models.URLField(blank=True, help_text='Enter the URL for the product datasheet', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
