# Generated by Django 5.2.4 on 2025-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0014_product_documentation_label_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('login_required', 'Login Required')], default='public', help_text='Choose who can see the price of this product', max_length=20),
        ),
    ]
