# Generated by Django 5.2.5 on 2025-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0016_alter_product_image_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('fire_safety', 'Fire Safety'), ('ict', 'ICT'), ('solar', 'Solar')], default='fire_safety', max_length=50),
        ),
    ]
