# Generated by Django 5.2.5 on 2025-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0019_alter_blog_options_alter_blog_excerpt_and_more'),
    ]

    operations = [
         migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(unique=True, blank=True),
        ),
    ]
