# Generated by Django 5.2.5 on 2025-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0020_auto_20251006_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Custom SEO description (max 155 chars). Leave blank for auto-generated description.', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (max 60 chars). Leave blank for auto-generated title.', max_length=60, null=True),
        ),
    ]
