# Generated by Django 5.2.5 on 2025-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0021_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Product brand (e.g., Eaton, Apollo, Giganet)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit / Model Number (e.g., EFCP-123)', max_length=100, null=True),
        ),
    ]
