# Generated by Django 5.2.5 on 2025-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0022_product_brand_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark this product to appear in the Popular Products carousel'),
        ),
    ]
