# Generated by Django 5.2.5 on 2025-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0023_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark this product as popular to feature it on the homepage carousel'),
        ),
    ]
