# Generated by Django 5.2.5 on 2025-12-04 06:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0024_alter_product_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text="Internal name for this campaign (e.g., 'Black Friday 2024')", max_length=255)),
                ('display_mode', models.CharField(choices=[('standard', 'Standard Hero Slide'), ('poster', 'Poster Only')], default='standard', help_text='Choose between standard hero slide or promotional poster', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Toggle to show/hide this banner on the website')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first (e.g., 0 appears before 1)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: Auto-activate banner on this date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Auto-deactivate banner after this date', null=True)),
                ('poster_image', cloudinary.models.CloudinaryField(blank=True, help_text='Full-width promotional poster image (for Poster mode)', max_length=255, null=True, verbose_name='poster')),
                ('poster_link', models.URLField(blank=True, help_text='Optional clickable link for the poster (e.g., /category/fire-alarms)', null=True)),
                ('title', models.CharField(blank=True, help_text='Main heading (for Standard mode)', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Small text above title (for Standard mode)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Hero description text (for Standard mode)')),
                ('button_text', models.CharField(blank=True, default='Explore Products', help_text='CTA button text (for Standard mode)', max_length=100)),
                ('button_link', models.CharField(blank=True, help_text='CTA button link (for Standard mode)', max_length=500)),
                ('image_1', cloudinary.models.CloudinaryField(blank=True, help_text='First product image (for Standard mode)', max_length=255, null=True, verbose_name='image_1')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, help_text='Second product image (for Standard mode)', max_length=255, null=True, verbose_name='image_2')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, help_text='Third product image (for Standard mode)', max_length=255, null=True, verbose_name='image_3')),
                ('layout', models.CharField(choices=[('three_images', 'Three Images'), ('two_images', 'Two Images'), ('single_image', 'Single Image')], default='three_images', help_text='Image layout for Standard mode', max_length=20)),
                ('background_class', models.CharField(blank=True, default='heroSlide1', help_text='CSS class for background styling (e.g., heroSlide1, heroSlide2)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner / Promotional Poster',
                'verbose_name_plural': 'Hero Banners / Promotional Posters',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
